# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: targetnav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    agents:
      main_agent:
        height: 0.2
        radius: 0.17
        sim_sensors:
          rgb_sensor:
            width: 320
            height: 240
            position: [0.0, 0.15, 0.0]
            hfov: 69
          depth_sensor:
            width: 320
            height: 240
            position: [0.0, 0.15, 0.0]
            hfov: 73
    forward_step_size: 0.1
