defaults:
  - task_config_base
  - actions:
      - move_forward
      - turn_left
      - turn_right
  - measurements:
      - distance_to_goal
      - success
      - spl
      - distance_to_goal_reward
      - top_down_map
  - _self_

type: TargetNav-v0
end_on_success: True
reward_measure: "distance_to_goal_reward"
success_measure: "nonstop_euclidean_success"
slack_reward: 0.0
