# @package habitat.dataset

defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_

type: TargetNav-v0
split: train
data_path: data/datasets/targetnav/meeting_room_w_ceiling/empty/{split}/{split}.json.gz
